"""Initial database structure

Revision ID: 17d43b382de8
Revises: 
Create Date: 2025-05-31 20:48:56.745489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17d43b382de8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('personnummer', sa.String(length=11), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('postal_code', sa.String(length=5), nullable=True),
    sa.Column('guardian_info', sa.String(length=100), nullable=True),
    sa.CheckConstraint("personnummer ~ '^\\d{6}-\\d{4}$'", name='valid_personnummer_format'),
    sa.CheckConstraint("phone ~ '^\\+46\\s*\\(\\d{1,4}\\)\\s*\\d{3}\\s*\\d{2}\\s*\\d{2}$'", name='valid_phone_format'),
    sa.CheckConstraint("postal_code ~ '^\\d{5}$'", name='valid_postal_code_format'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('personnummer')
    )
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_number', sa.String(length=24), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("account_number ~ '^SE8902[A-Z]{4}\\d{14}$'", name='valid_account_number_format'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_number')
    )
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('sender_country', sa.String(length=50), nullable=True),
    sa.Column('sender_municipality', sa.String(length=50), nullable=True),
    sa.Column('receiver_country', sa.String(length=50), nullable=True),
    sa.Column('receiver_municipality', sa.String(length=50), nullable=True),
    sa.Column('transaction_type', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    op.drop_table('accounts')
    op.drop_table('customers')
    # ### end Alembic commands ###
