"""Add bank table and relationships

Revision ID: aa1c006394e2
Revises: 17d43b382de8
Create Date: 2025-05-31 21:00:20.135030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa1c006394e2'
down_revision: Union[str, None] = '17d43b382de8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('banknr', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('banknr')
    )
    op.add_column('accounts', sa.Column('bank_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'accounts', 'banks', ['bank_id'], ['id'])
    op.add_column('customers', sa.Column('bank_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'customers', 'banks', ['bank_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'customers', type_='foreignkey')
    op.drop_column('customers', 'bank_id')
    op.drop_constraint(None, 'accounts', type_='foreignkey')
    op.drop_column('accounts', 'bank_id')
    op.drop_table('banks')
    # ### end Alembic commands ###
